### ISSUE TITLE
this doesnt work

### ISSUE THREAD

**Issue by Z1nerb** [munannoo/code-claimer#2]
i followed step by step the instructions and it doesnt work

**Comment by karsact** [comment]
true

**Comment by karsact** [comment]
> i followed step by step the instructions and it doesnt work

true

**Comment by munannoo** [comment]
added requirements.txt. You guys probably didnt download them. I forgot to keep them as well.

**Comment by munannoo** [comment]
added requirements.txt. You guys probably didnt download them. I forgot to keep them as well.
